/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPopularRouteImport } from './routes/admin/popular'
import { Route as AdminLogoutRouteImport } from './routes/admin/logout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminItemsRouteImport } from './routes/admin/items'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPopularRoute = AdminPopularRouteImport.update({
  id: '/admin/popular',
  path: '/admin/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/admin/logout',
  path: '/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/admin/__layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/popular': typeof AdminPopularRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/popular': typeof AdminPopularRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/__layout': typeof Admin_layoutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/popular': typeof AdminPopularRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/items'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/popular'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/items'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/popular'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin/__layout'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/items'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/popular'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminPopularRoute: typeof AdminPopularRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/popular': {
      id: '/admin/popular'
      path: '/admin/popular'
      fullPath: '/admin/popular'
      preLoaderRoute: typeof AdminPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/admin/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Admin_layoutRoute: Admin_layoutRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminPopularRoute: AdminPopularRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
